# Generated by Django 5.2.14 on 2026-05-09 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_author_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='management.category'),
            preserve_default=False,
        ),
    ]
